#!/bin/bash

#PBS -l nodes=1:ppn=1,walltime=24:00:00
#PBS -N fst
#PBS -m abe
#PBS -M cxb585@psu.edu
#PBS -e localhost:${PBS_O_WORKDIR}/${PBS_JOBNAME}.e${PBS_JOBID}.${PBS_ARRAYID}
#PBS -o localhost:${PBS_O_WORKDIR}/${PBS_JOBNAME}.o${PBS_JOBID}.${PBS_ARRAYID}

# Call with qsub -t 1-3 pbs/compute_Fst.pbs

# ------------------------------------------------------------------------------
# Variables
# ------------------------------------------------------------------------------

working_dir=$PBS_O_WORKDIR
export PATH=$PATH:$HOME/bin

# ----------------------------------------------------------------------------------------
# --- Calculate Fst on a per-SNP and windowed basis
# ----------------------------------------------------------------------------------------

cd $working_dir

IN_VCFS=( data/AGRHUM_EASTERN_100x267251.vcf.gz
          results/AGRHUM_EASTERN_100x267251.syn.vcf.gz
          results/AGRHUM_EASTERN_100x267251.nonsyn.vcf.gz
        )

INDEX=$(($PBS_ARRAYID - 1))

sh scripts/compute_Fst.sh ${IN_VCFS[$INDEX]}

exit
